### ISSUE TITLE
Add support for Hashicorp Vault

### ISSUE THREAD

**Issue by dimatha** [jakubfijalkowski/kvenv#1]
Hey ! Thanks for the great tool! I didn't do my research, but would it make sense to add Hashicorp Vault support? I believe there is a similar tool already available vault-cli and envconsul but I think adding support into kvenv would make is more "Swiss Army knife"

Thanks!

**Comment by jakubfijalkowski** [comment]
Hello! Thank you for the request! That indeed is a great idea. I don't have much of a experience with Vault, but this is a great moment to gain it. :)

I won't be able to implement it this week probably, but it will be done sometime soon-ish. :)

**Comment by dimatha** [comment]
No worries! Just an idea. 

Have a look at the two tools I’ve provided to get you started. 


thanks !

**Comment by jakubfijalkowski** [comment]
Took a little bit longer (the upgrade to newest Azure/Google libs & newest Clap was painful), but the work is done now.

I'm not fully sure that all the necessary features of Vault are supported, but this should be usable in some cases. :)
