### ISSUE TITLE
Error: cannot load the environment

### ISSUE THREAD

**Issue by aasier** [jakubfijalkowski/kvenv#3]
Hi! @jakubfijalkowski 

I´m testing your solution to get information from a Keyvault, and I´m getting this error when I run the ./kvenv

**OS**: Debian (bookworm/sid)
**kvenv**: kvenv 0.2.0

```
./kvenv cache --azure \
--azure-tenant-id "xx-xxx-xxx-xx-xxxxx" \
--azure-client-id "xxx-xx-xx-x-xxxxxxxx" \
--azure-client-secret "xxxxxxx" \
--secret-name test \
--azure-keyvault-name keyvault-atlantis-lab \
-d /root/

```

Error output:

```
Error: cannot load the environment

Caused by:
    expected value at line 1 column 1
```

Could you please help us?
Thanks!
Asier

**Comment by jakubfijalkowski** [comment]
Hey! v0.2 requires libssl 1.1 and as far as I can see, bookworm does not have it - can you send me how you installed it? I think it might be the reason for that as I can't really pinpoint the issue.

Also, it might be worth trying v0.3 - it switched from using `native-tls` to `rustls` for most of the operations (and works with OpenSSL 3 distributed with Bookworm). It also uses much newer version of Azure KV client so should be much more stable (with better error messages).

EDIT: v0.3.1 uses rustls-only, so you can check it out also.

**Comment by aasier** [comment]
Morning,
Still having the same issue with the new version `v0.3.1`,
I'm running `kvenv` into a fresh ubuntu docker machine, and I only installed the typical tools like vim, wget, curl to start testing your tool.

How am I installing the tool? Only downloading the binary from the release, changing the grants of the file in my ubuntu-docker and run it with the parameters that showed in my previous comment,
Maybe I've got it all wrong.

Thanks in advance!! ;)

![image](https://user-images.githubusercontent.com/17740475/216924863-df8c7857-473c-4903-8303-5c4c6b7f36ef.png)

```
root@test:/# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
**UBUNTU_CODENAME=jammy**
```

**Comment by jakubfijalkowski** [comment]
Morning!

That's quite a nasty bug. I'll investigate it this evening and try to pinpoint where the error is returned - I haven't seen that yet.

**Comment by jakubfijalkowski** [comment]
Okay, I found the issue. Much more... sensible than I initially anticipated. ;)

When running kvenv with a secret name, it expects a single key, but the value _must be a valid JSON object_. Unfortunately, the error handling there was sub-par and it reported serde error directly. I changed that in v0.3.2 and now it describes what went wrong.

Setting the value to JSON object should solve the issue.

**Comment by aasier** [comment]
Great!!!
Now it works! and sorry, I forgot to explain how I saved the secret into the Azure Keyvault.

The error output now it's clear.

```bash
Error: cannot load the environment

Caused by:
    0: cannot decode secret - it is not a valid JSON
    1: expected value at line 1 column 1
```

Another small thing to fix, the version in the `--version` option, it said that we are in the `0.3.1 `instead of `0.3.2`

```bash
./kvenv --version
kvenv 0.3.1 
```

Thanks for your support! ;)

**Comment by jakubfijalkowski** [comment]
I need to switch to a different way of releasing things... Thanks for noting the mismatched version!
